target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '8.2.0' # latest version
end

# pod 'GoogleMaps', '8.2.0'

# pod 'GoogleMaps', '7.4.0'
# pod 'Google-Maps-iOS-Utils', '4.2.2'
