target 'iosApp' do
  use_frameworks!
  platform :ios, '15.4'  # ios.deploymentTarget
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '8.4.0' # latest version
end

# pod 'GoogleMaps', '7.4.0'
# pod 'Google-Maps-iOS-Utils', '4.2.2'
